apiVersion: v1
kind: Service
metadata: 
    name: mysql-bill-service
    labels: ##Labels that will be applied to the resource
        app: mysql-bill-service-app
spec: 
    ports: 
      - port: 3306
        targetPort: 3306
    clusterIP: None  #This is also termed as Headless service, where ClusterId is NOne...
    selector:  ##SELECT ANY POD WITH LABEL mysql-app AND OPTIONAL TIER
        app: mysql-bill-app-pod

---
apiVersion: v1
kind: PersistentVolume
metadata: 
    name: mysql-bill-pv
    labels: 
       app: mysql-bill-pv-app 
spec: 
    storageClassName: standard
    capacity: 
        storage: 256Mi
    accessModes: 
        - ReadWriteOnce
    hostPath: 
        path: "/Users/cpandey/dev/docker-data/restaurant/k8/mysql-bill" #LOCAL PATH TO THE SYSTEM 
    persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: mysql-bill-pvc
    labels: 
       app: mysql-bill-pvc-app
    
spec: 
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources: 
        requests:
           storage: 250Mi 

---
apiVersion: v1
kind: ConfigMap
metadata: 
    name: mysql-bill-init-script
data:
    init-script.sql:  |
        CREATE DATABASE IF NOT EXISTS billdb;
        USE billdb;
        CREATE TABLE address (id BIGINT NOT NULL, city VARCHAR(255), country VARCHAR(255), line1 VARCHAR(255), line2 VARCHAR(255), STATE VARCHAR(255), PRIMARY KEY (id)) engine=InnoDB;
        CREATE TABLE hibernate_sequence (next_val BIGINT) engine=InnoDB;
        INSERT INTO hibernate_sequence VALUES ( 1 );
        CREATE TABLE bills (id BIGINT NOT NULL, bill_date VARCHAR(255), bill_time VARCHAR(255), status INTEGER, delivery_address_id BIGINT, PRIMARY KEY (id)) engine=InnoDB;
        ALTER TABLE bills ADD CONSTRAINT bill_fk FOREIGN KEY (delivery_address_id) REFERENCES address (id);
         
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
    name: mysql-bill-server
    labels:   
        app: mysql-bill-server-app
spec: 
    selector: 
        matchLabels:
            app: mysql-bill-app-pod

    serviceName: mysql-h  #Headless Service Name #Master DNS Become: mysql-0.mysql-h.default.svc.cluster.local, mysql-1.mysql-h.default.svccluster.lcoal
    replicas: 1
    template: 
        metadata: 
            name: mysql-bill-pod
            labels: 
                app: mysql-bill-app-pod
        spec: 
            containers: 
                - name: mysql-container
                  image:  mysql/mysql-server:8.0.23
                  imagePullPolicy: IfNotPresent
                  
                  ports:
                    - containerPort: 3306
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      value: root

                    - name: MYSQL_USER
                      value: cpandey

                    - name: MYSQL_PASSWORD
                      value: chandan@1234

                    - name: MYSQL_DATABASE
                      value: billdb

                  volumeMounts: 
                    - name: mysql-initdb ##MOUNT PATH FOR INITIAL SCRIPT TO RUN ON DB
                      mountPath: /docker-entrypoint-initdb.d

                    - name: mysql-server-storage
                      mountPath: /var/lib/mysql

            volumes:
                - name: mysql-initdb
                  configMap: 
                    name: mysql-bill-init-script
    
                - name: mysql-server-storage
                  persistentVolumeClaim: 
                      claimName:  mysql-bill-pvc

 
##DNS Entry {Headless Ref} is created only in 2 condition: 
# spec section of the POD have 2 optional conf: subdomain, which shouldbe equal to name of service (mysql-h). It create subdomain: mysql-h.default.svc.cluster.lcoal
##StatefulSet does not require the above condition. 
## second: define hostname: as mysql-pod

