version: "3.8"

services:
  billing_data_db:
    container_name: billing-percona-db
    platform: linux/x86_64
    image: percona:ps-5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_BILLING_DATABASE
      - MYSQL_ROOT_HOST="%"
    ports:
      - $MYSQLDB_BILLING_LOCAL_PORT:$MYSQLDB_BILLING_DOCKER_PORT
    volumes:
      - type: bind 
        source: $BASE_LOC/$BILLING_MYSQL_DATA_LOC 
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: $BASE_LOC/$BILLING_INITIAL_SCRIPT_LOC
        target: /docker-entrypoint-initdb.d/1.sql
        volume:
          nocopy: true
  billing_web_app:
      depends_on:
        - billing_data_db
      container_name: billing-web-app
      build:
        context: ./ 
        dockerfile: Dockerfile
      restart: on-failure
      env_file: ./.env
      ports:
        - $BILLING_WEB_LOCAL_PORT:$BILLING_DOCKER_WEB_PORT
      environment:
          "SPRING_DATASOURCE_URL": "$MYSQLDB_BILLING_URL"
          "SPRING_DATASOURCE_USERNAME" : "$DB_USER"
          "SPRING_DATASOURCE_PASSWORD" : "$DB_PASSWORD"
          "SPRING_DATASOURCE_DRIVER_CLASS_NAME": "com.mysql.cj.jdbc.Driver"
      volumes:
        - type: bind
          source: $BASE_LOC/$BILLING_LOG_LOC
          target: /opt/multimoduleprojects/restaurant/billing/logs
          volume:
            nocopy: true
      stdin_open: true
      tty: true

 