piVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
    name: itlogiclab-path-based-routing-rules
    namespace: default
    annotations: 
       nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  rules:
  - http: 
     paths: 
     - path: /billing
       pathType: Prefix
       backend: 
        service: 
           name: billing-service
           port: 
             number: 20001
     - path: /order
       pathType: Prefix
       backend: 
        service: 
            name: order-service
            port: 
              number: 20001